<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class SetorHafalan extends Model
{
    protected $guarded = ['id'];

    public function siswa(): BelongsTo
    {
        return $this->belongsTo(Siswa::class);
    }
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    const NILAI_HAFALAN = [
        'Mumtaz' => 'Mumtaz',
        'Jayyid Jiddan' => 'Jayyid Jiddan',
        'Jayyid' => 'Jayyid',
        'Maqbul' => 'Maqbul',
        'Naqis' => 'Naqis',
    ];

    const SURAT_ALQURAN = [
    'Al-Fatihah' => 'Al-Fatihah',
    'Al-Baqarah' => 'Al-Baqarah',
    'Ali \'Imran' => 'Ali \'Imran',
    'An-Nisa\' ' => 'An-Nisa\' ',
    'Al-Ma\'idah' => 'Al-Ma\'idah',
    'Al-An\'am' => 'Al-An\'am',
    'Al-A\'raf' => 'Al-A\'raf',
    'Al-Anfal' => 'Al-Anfal',
    'At-Tawbah' => 'At-Tawbah',
    'Yunus' => 'Yunus',
    'Hud' => 'Hud',
    'Yusuf' => 'Yusuf',
    'Ar-Ra\'d' => 'Ar-Ra\'d',
    'Ibrahim' => 'Ibrahim',
    'Al-Hijr' => 'Al-Hijr',
    'An-Nahl' => 'An-Nahl',
    'Al-Isra\'' => 'Al-Isra\'',
    'Al-Kahf' => 'Al-Kahf',
    'Maryam' => 'Maryam',
    'Taha' => 'Taha',
    'Al-Anbiya\'' => 'Al-Anbiya\'',
    'Al-Hajj' => 'Al-Hajj',
    'Al-Mu\'minun' => 'Al-Mu\'minun',
    'An-Nur' => 'An-Nur',
    'Al-Furqan' => 'Al-Furqan',
    'Ash-Shu\'ara\'' => 'Ash-Shu\'ara\'',
    'An-Naml' => 'An-Naml',
    'Al-Qasas' => 'Al-Qasas',
    'Al-Ankabut' => 'Al-Ankabut',
    'Ar-Rum' => 'Ar-Rum',
    'Luqman' => 'Luqman',
    'As-Sajdah' => 'As-Sajdah',
    'Al-Ahzab' => 'Al-Ahzab',
    'Saba\'' => 'Saba\'',
    'Fatir' => 'Fatir',
    'Ya-Sin' => 'Ya-Sin',
    'As-Saffat' => 'As-Saffat',
    'Sad' => 'Sad',
    'Az-Zumar' => 'Az-Zumar',
    'Ghafir' => 'Ghafir',
    'Fussilat' => 'Fussilat',
    'Ash-Shura' => 'Ash-Shura',
    'Az-Zukhruf' => 'Az-Zukhruf',
    'Ad-Dukhan' => 'Ad-Dukhan',
    'Al-Jathiyah' => 'Al-Jathiyah',
    'Al-Ahqaf' => 'Al-Ahqaf',
    'Muhammad' => 'Muhammad',
    'Al-Fath' => 'Al-Fath',
    'Al-Hujurat' => 'Al-Hujurat',
    'Qaf' => 'Qaf',
    'Adh-Dhariyat' => 'Adh-Dhariyat',
    'At-Tur' => 'At-Tur',
    'An-Najm' => 'An-Najm',
    'Al-Qamar' => 'Al-Qamar',
    'Ar-Rahman' => 'Ar-Rahman',
    'Al-Waqi\'ah' => 'Al-Waqi\'ah',
    'Al-Hadid' => 'Al-Hadid',
    'Al-Mujadilah' => 'Al-Mujadilah',
    'Al-Hashr' => 'Al-Hashr',
    'Al-Mumtahanah' => 'Al-Mumtahanah',
    'As-Saff' => 'As-Saff',
    'Al-Jumu\'ah' => 'Al-Jumu\'ah',
    'Al-Munafiqun' => 'Al-Munafiqun',
    'At-Taghabun' => 'At-Taghabun',
    'At-Talaq' => 'At-Talaq',
    'At-Tahrim' => 'At-Tahrim',
    'Al-Mulk' => 'Al-Mulk',
    'Al-Qalam' => 'Al-Qalam',
    'Al-Haqqah' => 'Al-Haqqah',
    'Al-Ma\'arij' => 'Al-Ma\'arij',
    'Nuh' => 'Nuh',
    'Al-Jinn' => 'Al-Jinn',
    'Al-Muzzammil' => 'Al-Muzzammil',
    'Al-Muddaththir' => 'Al-Muddaththir',
    'Al-Qiyamah' => 'Al-Qiyamah',
    'Al-Insan' => 'Al-Insan',
    'Al-Mursalat' => 'Al-Mursalat',
    'An-Naba\'' => 'An-Naba\'',
    'An-Nazi\'at' => 'An-Nazi\'at',
    'Abasa' => 'Abasa',
    'At-Takwir' => 'At-Takwir',
    'Al-Infitar' => 'Al-Infitar',
    'Al-Mutaffifin' => 'Al-Mutaffifin',
    'Al-Inshiqaq' => 'Al-Inshiqaq',
    'Al-Buruj' => 'Al-Buruj',
    'At-Tariq' => 'At-Tariq',
    'Al-A\'la' => 'Al-A\'la',
    'Al-Ghashiyah' => 'Al-Ghashiyah',
    'Al-Fajr' => 'Al-Fajr',
    'Al-Balad' => 'Al-Balad',
    'Ash-Shams' => 'Ash-Shams',
    'Al-Layl' => 'Al-Layl',
    'Ad-Duha' => 'Ad-Duha',
    'Ash-Sharh' => 'Ash-Sharh',
    'At-Tin' => 'At-Tin',
    'Al-Alaq' => 'Al-Alaq',
    'Al-Qadr' => 'Al-Qadr',
    'Al-Bayyinah' => 'Al-Bayyinah',
    'Az-Zalzalah' => 'Az-Zalzalah',
    'Al-Adiyat' => 'Al-Adiyat',
    'Al-Qari\'ah' => 'Al-Qari\'ah',
    'At-Takathur' => 'At-Takathur',
    'Al-Asr' => 'Al-Asr',
    'Al-Humazah' => 'Al-Humazah',
    'Al-Fil' => 'Al-Fil',
    'Quraish' => 'Quraish',
    'Al-Ma\'un' => 'Al-Ma\'un',
    'Al-Kawthar' => 'Al-Kawthar',
    'Al-Kafirun' => 'Al-Kafirun',
    'An-Nasr' => 'An-Nasr',
    'Al-Masad' => 'Al-Masad',
    'Al-Ikhlas' => 'Al-Ikhlas',
    'Al-Falaq' => 'Al-Falaq',
    'An-Nas' => 'An-Nas',
    ];
}
